version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway_image
    container_name: shareit_gateway_container
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server_image
    container_name: shareit_server_container
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  db:
    image:  postgres:15.3-alpine
    container_name: shareit_db_postgres_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
